name: Release

on:
  repository_dispatch:
    types: [ release ]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-deploifai repo
        uses: actions/checkout@v3
        with:
          path: homebrew-deploifai

      - name: Checkout cli repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          repository: deploifai/cli
          ref: ${{ github.event.client_payload.ref }}
          path: cli

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requirements and deploifai-cli
        working-directory: cli
        run: |
          pip install -U pip wheel setuptools
          pip install --editable .
          pip install homebrew-pypi-poet

      - name: Generate homebrew formula
        working-directory: cli
        run: |
          poet --formula deploifai > deploifai.rb
          mv deploifai.rb $GITHUB_WORKSPACE/homebrew-deploifai/release/deploifai.rb

      - name: Re-generate formula in homebrew-deploifai repo
        working-directory: homebrew-deploifai/release
        run: |
          python generate.py ${{ github.event.client_payload.version }}

      - name: Echo
        working-directory: homebrew-deploifai/Formula
        run: |
          cat deploifai.rb

#      - name: Commit, push, and create pull request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          path: homebrew-deploifai
#          add-paths: "Formula/deploifai.rb"
#          commit-message: "Update formula to ${{ github.event.client_payload.version }}"
#          title: "Update formula to ${{ github.event.client_payload.version }}"
#          body: "Please verify the formula and merge the PR."
#          branch: ${{ github.event.client_payload.version }}
#          base: main
#          delete-branch: true
